name: pinnacle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip

  # core numerics
  - numpy=1.23.5
  - scipy=1.15.1
  - pandas=2.2.3

  # plotting / utils (optional but common)
  - matplotlib=3.10.0

  # other packages
  - packaging=25.0
  - pyyaml=6.0.2
  - click=7.1.1
  - glob2

  # pip packages
  - pip:
      - ase==3.25.0
      - protobuf==3.9.2
      - tidynamics==1.1.2
      - numba==0.60.0
      - e3nn==0.4.4
      - mace-torch==0.3.13